language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: CbcVAarvTC8isod6seH+qAJLBO5IJeFzf2QQJGZxcinnH7OQLk96kXyDXD1idC43IpZ2CVqPPJknrdiT1jFXrrgV4daO+Hi+HZnJ+7nRs3yLna1gg2k/DbD/PdsS+2wGMy1yPM6Pvt/PHkwKZgOlQUswn30eMKP8k1FVSi7Dk7qS3z9PFI4y+mL4QG0qwNGzLNJ9k/ulE74Deq0Yi/lpKoiJoOBydfkGxZGtm+HIIkTX3NqwW1yUbsJFb1eRCNv7o2BBQffKZbFllweLi6sUUwWkZpFR6rN+vOfeakafGrxjsN+CaZc9HpMoB16CiXLrwnkTfTqVdBXo8B0LGLEKKsvR/olFBtkkUDgc+95QPjaZ9WBu7uHcXT/LG5BNORDP4/lDjD0RmirAZgSwDKEXg2vA/ZJEmJJaSQ1bUyRgsIjMw98EU0B41aA3MNlpacLO2rxeGHIUroZ2s1JuJWM4Udx2RKDtTk6cx8/e8RSozdv6ncqIvpKGoVzaKb/UA350DRAIiNWKvFToTwDKgNvZS7a/1FGOYUxMH02FPQtyqznEUJhKk2WK2fFAZeGhOZG0c8eBYRg4Vhh/rdTMA52aSnO9Zeaotez5IzPWVmuUw5weDbtRBDS8cWLrCi9eKMLy4v0kJeSRh1/XYZwzWdyZI7FzIaKraeqJTWg9rhJRiaI=
  app: rocky-journey-76857
  on:
    repo: Btan579/test-restaurants-ci
    branch: feature/with-tests
